LeaveManagementSystem/Controllers/DepartmentController.cs
using AutoMapper;
using LeaveManagementSystem.Models;
using LeaveManagementSystem.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Scaffolding.Metadata;
using System.Security.Permissions;

namespace LeaveManagementSystem.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly LMDbContext _dbContext;
        private readonly IMapper _mapper;


        public DepartmentController(LMDbContext dbContext, IMapper mapper)
        {
            _dbContext = dbContext;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            var data = _dbContext.Departments;
            return View(_mapper.ProjectTo<DepartmentViewModel>(data));


            //if (data != null && data.Count() > 0)
            //{

            //    return View(_mapper.ProjectTo<DepartmentViewModel>(data));


            //}
            //else
            //{
            //    return View(data);
            //}


        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Department department)
        {
            _dbContext.Add(department);
            _dbContext.SaveChanges();
            return RedirectToAction("Index");
        }
        //get 
        public IActionResult Edit(int? id)
        {
            if (id == null)
                return RedirectToAction("Index");
            var data = _dbContext.Departments.Find(id);
            if (data == null)
                return RedirectToAction("Index");
            return View(data);
        }

        [HttpPost]
        public IActionResult Edit(Department department)
        {
            _dbContext.Update(department);
            _dbContext.SaveChanges();
            return RedirectToAction("Index");
        }


        public IActionResult Delete(int? id)
        {
            if (id == null)

                return RedirectToAction("Index");
            var data = _dbContext.Departments.Find(id);

            if (data == null)

                return RedirectToAction("Index");
            return View(data);




        }

        [HttpPost]
        public IActionResult Delete(Department department)
        {
            _dbContext.Remove(department);
            _dbContext.SaveChanges();
            return RedirectToAction("index");
        }

        public IActionResult Details(int? id)
        {
            if(id == null)
                return RedirectToAction("Index");
            var details = _dbContext.Departments.Find(id);
                if(details == null)
                return RedirectToAction("Index");
            return View(details);

        }
      

    }
}

LeaveManagementSystem/Controllers/DesignationController.cs
using AutoMapper;
using LeaveManagementSystem.Models;
using Microsoft.AspNetCore.Mvc;

namespace LeaveManagementSystem.Controllers
{
    public class DesignationController : Controller
    {
        private readonly LMDbContext _dbContext;
        private readonly IMapper _mapper;

        public DesignationController(LMDbContext dbContext, IMapper mapper)
        {
            _dbContext = dbContext;
            _mapper = mapper;   
        }

        public IActionResult Index()
        {
            var data = _dbContext.Designations.ToList();
            return View(data);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Designation designation)
        {
            _dbContext.Add(designation);
            _dbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
                return RedirectToAction("Index");
            var data = _dbContext.Designations.Find(id);
            if (data == null)
                return RedirectToAction("Index");
            return View(data);
        }

        [HttpPost]
        public IActionResult Edit(Designation designation)
        {
            _dbContext.Update(designation);
            _dbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int? id)
        {
            if(id == null)
                return RedirectToAction("Index");
            var data = _dbContext.Designations.Find(id);
            if(data == null)
                return RedirectToAction("Index");
            return View(data);
        }
        [HttpPost]
        public IActionResult Delete(Designation designation)
        {
            _dbContext.Remove(designation);
            _dbContext.SaveChanges();
            return RedirectToAction("Index");   
        }

            
    }
}

LeaveManagementSystem/Controllers/EmployeeController.cs
using AutoMapper;
using LeaveManagementSystem.Models;
using LeaveManagementSystem.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Conventions;
using System.Diagnostics;


namespace LeaveManagementSystem.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly LMDbContext _dbContext;
        private readonly IMapper _mapper;
        public EmployeeController(LMDbContext dbContext, IMapper mapper)
        {
            _dbContext = dbContext;
            _mapper = mapper;
        }




        //public EmployeeController(IMapper mapper)
        //{
        //    _mapper = mapper;
        //}


        public ActionResult Index()
        {

            // var hvhghg = _dbContext.Employees.ToList();

            DbSet<Employee> LMDbContext = _dbContext.Employees;
            List<EmployeeListViewModel> gccgc = _mapper.ProjectTo<EmployeeListViewModel>(LMDbContext).ToList();
            //var employee = _dbContext.Employees;

            return View(gccgc);
        }








        public ActionResult Create()
        {
            var departments = _dbContext.Departments.Select(department => new SelectListItem
            {
                Text = department.Name,
                Value = department.Id.ToString()
            }).ToList();

            ViewData["departments"] = departments;

            var designations = _dbContext.Designations.Select(designation => new SelectListItem
            {
                Text = designation.Name,
                Value = designation.Id.ToString()
            }).ToList();
            ViewData["designations"] = designations;
            return View();

        }

        [HttpPost]
        public ActionResult Create(Employee employee)
        {



            _dbContext.Add(employee);
            _dbContext.SaveChanges();

            return RedirectToAction("Index");




        }
        public IActionResult Edit(int? id)
        {
            if (id == null)
                return RedirectToAction("Index");
            var departments = _dbContext.Departments.Select(department => new SelectListItem
            {
                Text = department.Name,
                Value = department.Id.ToString()
            }).ToList();

            ViewData["departments"] = departments;

            var designations = _dbContext.Designations.Select(designation => new SelectListItem
            {
                Text = designation.Name,
                Value = designation.Id.ToString()
            }).ToList();
            ViewData["designations"] = designations;


            var data = _dbContext.Employees.Where(x => x.Id == id);
            EmployeeUpdateViewModel? ujjwal = _mapper.ProjectTo<EmployeeUpdateViewModel>(data).FirstOrDefault();
            if (ujjwal == null)
                return RedirectToAction("Index");
            return View(ujjwal);
        }

        [HttpPost]
        public IActionResult Edit(EmployeeUpdateViewModel employee)
        {
            Employee data = _dbContext.Employees.Where(x => x.Id == employee.Id).First();
            _mapper.Map(employee, data);
            _dbContext.Update(data);
            _dbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int? id)
        {
            //var data = _dbContext.Employees.Find(id);
            //return View(data);
            if (id == null)
                return RedirectToAction("Index");
            var data = _dbContext.Employees.Find(id);
            if (data == null)
                return RedirectToAction("Index");
            return View(data);


        }
        [HttpPost]
        public IActionResult Delete(Employee employee)
        {
            _dbContext.Remove(employee);
            _dbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
                return RedirectToAction("Index");

            IQueryable<Employee> data = _dbContext.Employees.Where(x => x.Id == id);


            var ujjwal = _mapper.ProjectTo<EmployeeDetailsViewModel>(data).FirstOrDefault();
            if (ujjwal == null)
                return RedirectToAction("Index");

            return View(ujjwal);
        }



    }

}

LeaveManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LeaveManagementSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LeaveManagementSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LeaveManagementSystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">employee    </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Department</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Designation" asp-action="Index">Designation</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - LeaveManagementSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>