LeaveManagementSystem/Models/Employee.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LeaveManagementSystem.Models
{
    public class Employee
    {
        [Key]
        public int Id{ get; set; }
        [Required]
        [StringLength(50)]
        public string  Name { get; set; }

        [Required]
        [StringLength(100)]
        public string Address { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public DateTime DateOFBirth{ get; set; }

        [DisplayName("Date Of Join")]
        [DataType(DataType.Date)]
        [Required]
        public DateTime DateOfJoin { get; set; }

        [Required(ErrorMessage = "You must provide a phone number")]
        [Display(Name = "ContactNumber")]
        [DataType(DataType.PhoneNumber)]

        public string ContactNumber { get; set; }

        [Required(ErrorMessage = "Email is required.")]
        [EmailAddress]
     
        public string? Email { get; set; }


        public Department Department{ get; set; }
        [ForeignKey(nameof(Department))]
        public int DepartmentId { get; set; }


        public Designation Designation { get; set; }
        [ForeignKey(nameof(Designation))]
        public int DesignationId { get; set; }
    }
}

LeaveManagementSystem/Models/ViewModel/EmployeeViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace LeaveManagementSystem.Models.ViewModel
{
    public class EmployeeViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        [Required]
        [StringLength(100)]
        public string Address { get; set; }

        [Required(ErrorMessage = "You must provide a phone number")]
        [Display(Name = "ContactNumber")]
        [DataType(DataType.PhoneNumber)]

        public string ContactNumber { get; set; }
        public string Email { get; set; }

        [DataType(DataType.Date)]
        public DateTime DateOfJoin { get; set; }
        public string DepartmentName { get; set; }
        public string DesignationName { get; set; }
    }




    public class EmployeeListViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public string DesignationName { get; set; }
        public string ContactNumber { get; set; }

    }
    public class EmployeeUpdateViewModel
    {
        public int Id { get; set; }

        public string Address { get; set; }
        public string ContactNumber { get; set; }
        public string DepartmentId { get; set; }
        public string Email { get; set; }

        public int DesignationId { get; set; }
    }

    public class EmployeeDetailsViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public string Addresss { get; set; }
        public string ContactNumber { get; set; }
        [DataType(DataType.Date)]
        public DateTime DateOfJoin { get; set; }
        public string DepartmentName { get; set; }

        public string DesignationName { get; set; }




    }
}

LeaveManagementSystem/Controllers/EmployeeController.cs
using AutoMapper;
using LeaveManagementSystem.Models;
using LeaveManagementSystem.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Conventions;
using System.Diagnostics;


namespace LeaveManagementSystem.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly LMDbContext _dbContext;
        private readonly IMapper _mapper;
        public EmployeeController(LMDbContext dbContext, IMapper mapper)
        {
            _dbContext = dbContext;
            _mapper = mapper;
        }




        //public EmployeeController(IMapper mapper)
        //{
        //    _mapper = mapper;
        //}


        public ActionResult Index()
        {

            // var hvhghg = _dbContext.Employees.ToList();

            DbSet<Employee> LMDbContext = _dbContext.Employees;
            List<EmployeeListViewModel> gccgc = _mapper.ProjectTo<EmployeeListViewModel>(LMDbContext).ToList();
            //var employee = _dbContext.Employees;

            return View(gccgc);
        }








        public ActionResult Create()
        {
            var departments = _dbContext.Departments.Select(department => new SelectListItem
            {
                Text = department.Name,
                Value = department.Id.ToString()
            }).ToList();

            ViewData["departments"] = departments;

            var designations = _dbContext.Designations.Select(designation => new SelectListItem
            {
                Text = designation.Name,
                Value = designation.Id.ToString()
            }).ToList();
            ViewData["designations"] = designations;
            return View();

        }

        [HttpPost]
        public ActionResult Create(Employee employee)
        {



            _dbContext.Add(employee);
            _dbContext.SaveChanges();

            return RedirectToAction("Index");




        }
        public IActionResult Edit(int? id)
        {
            if (id == null)
                return RedirectToAction("Index");
            var departments = _dbContext.Departments.Select(department => new SelectListItem
            {
                Text = department.Name,
                Value = department.Id.ToString()
            }).ToList();

            ViewData["departments"] = departments;

            var designations = _dbContext.Designations.Select(designation => new SelectListItem
            {
                Text = designation.Name,
                Value = designation.Id.ToString()
            }).ToList();
            ViewData["designations"] = designations;


            var data = _dbContext.Employees.Where(x => x.Id == id);
            EmployeeUpdateViewModel? ujjwal = _mapper.ProjectTo<EmployeeUpdateViewModel>(data).FirstOrDefault();
            if (ujjwal == null)
                return RedirectToAction("Index");
            return View(ujjwal);
        }

        [HttpPost]
        public IActionResult Edit(EmployeeUpdateViewModel employee)
        {
            Employee data = _dbContext.Employees.Where(x => x.Id == employee.Id).First();
            _mapper.Map(employee, data);
            _dbContext.Update(data);
            _dbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int? id)
        {
            //var data = _dbContext.Employees.Find(id);
            //return View(data);
            if (id == null)
                return RedirectToAction("Index");
            var data = _dbContext.Employees.Find(id);
            if (data == null)
                return RedirectToAction("Index");
            return View(data);


        }
        [HttpPost]
        public IActionResult Delete(Employee employee)
        {
            _dbContext.Remove(employee);
            _dbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
                return RedirectToAction("Index");

            IQueryable<Employee> data = _dbContext.Employees.Where(x => x.Id == id);


            var ujjwal = _mapper.ProjectTo<EmployeeDetailsViewModel>(data).FirstOrDefault();
            if (ujjwal == null)
                return RedirectToAction("Index");

            return View(ujjwal);
        }



    }

}

LeaveManagementSystem/Controllers/LeaveController.cs
using LeaveManagementSystem.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace LeaveManagementSystem.Controllers
{
    public class LeaveController : Controller
    {
        private readonly LMDbContext _dbContext;
        public LeaveController(LMDbContext context)
        {
            _dbContext = context;
        }
        // GET: LeaveController
        public ActionResult Index()
        {
            return View();
        }

        // GET: LeaveController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        public IActionResult Create(int id)
        {
            var data = _dbContext.Employees.Where(x => x.Id == id).FirstOrDefault();
            return View(data);
        }
        [HttpPost]
        public IActionResult Create(Leave leave)
        {
            _dbContext.Add(leave);
            _dbContext.SaveChanges();
            return RedirectToAction("Index");

        }

        //// GET: LeaveController/Create
        //public ActionResult Create(int? id)
        //{
        //    var data  = _dbContext.Employees.Find(id);
        //    return View(data);
        //}

        //// POST: LeaveController/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(IFormCollection collection)
        //{
        //    var Employee = _dbContext.Employees.Select(Employee => new SelectListItem
        //    {
        //        Text = Employee.Name,
        //        Value = Employee.Id.ToString()
        //    }).ToList();

        //    ViewData["Employee"] = Employee;

        //    try
        //    {

        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        // GET: LeaveController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: LeaveController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LeaveController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: LeaveController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

LeaveManagementSystem/Views/Employee/Create.cshtml
@model LeaveManagementSystem.Models.Employee
@{
    ViewData["Title"] = "Create";
    var departments = ViewData["departments"] as IEnumerable<SelectListItem>;
    var designations = ViewData["designations"] as IEnumerable<SelectListItem>;
}

<h1>Create</h1>

<h4>Employee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOFBirth" class="control-label"></label>
                <input asp-for="DateOFBirth" class="form-control" />
                <span asp-validation-for="DateOFBirth" class="text-danger"></span>
            </div>
 
            <div class="form-group">
                <label asp-for="DateOfJoin" class="control-label"></label>
                <input asp-for="DateOfJoin" class="form-control" />
                <span asp-validation-for="DateOfJoin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactNumber" class="control-label"></label>
                <input asp-for="ContactNumber" class="form-control" />
                <span asp-validation-for="ContactNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartmentId" class="control-label"></label>
                <select asp-for=DepartmentId asp-items=departments class="form-control"></select>
                <span asp-validation-for="DepartmentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DesignationId" class="control-label"></label>
                <select asp-for=DesignationId asp-items=designations class="form-control"></select>
                <span asp-validation-for="DesignationId" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

LeaveManagementSystem/Views/Employee/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model LeaveManagementSystem.Models.Employee
@{
    ViewData["Title"] = "Delete";
}
@{
    <form method="post" asp-action="Delete">

        <label> You want to delete???</label>
        <button type="submit" class="btn btn-danger">Delete</button>
        <button asp-action="Index" class="btn btn-primary">cancel</button>

    </form>
}

LeaveManagementSystem/Views/Employee/Details.cshtml
@model LeaveManagementSystem.Models.ViewModel.EmployeeDetailsViewModel
@{
    ViewData["Title"] = "Details";
}

<tr>
<th>@Html.DisplayFor(modelItem => Model.Addresss)</th></br>
    <th>@Html.DisplayFor(modelItem => Model.Name)</th></br>
<th>@Html.DisplayFor(modelItem => Model.ContactNumber)</th</br>
<th>@Html.DisplayFor(modelItem => Model.DateOfJoin)</th</br>
<th>@Html.DisplayFor(modelItem => Model.DepartmentName)</th></br>
<th>@Html.DisplayFor(modelItem => Model.DesignationName)</th</br>
</tr>
  
<div>
    <a asp-action="Index">Back to List</a>
</div>

LeaveManagementSystem/Views/Employee/Edit.cshtml
@model LeaveManagementSystem.Models.ViewModel.EmployeeUpdateViewModel
@{
    ViewData["Title"] = "Edit";
    var departments = ViewData["departments"] as IEnumerable<SelectListItem>;
    var designations = ViewData["designations"] as IEnumerable<SelectListItem>;
}

<h1>Edit</h1>

<h4>Employee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
          
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
           

         
            <div class="form-group">
                <label asp-for="ContactNumber" class="control-label"></label>
                <input asp-for="ContactNumber" class="form-control" />
                <span asp-validation-for="ContactNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
       
            <div class="form-group">
                <label asp-for="DepartmentId" class="control-label"></label>
                <select asp-for=DepartmentId asp-items=departments class="form-control"></select>
                <span asp-validation-for="DepartmentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DesignationId" class="control-label"></label>
                <select asp-for=DesignationId asp-items=designations class="form-control"></select>
                <span asp-validation-for="DesignationId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="update" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

LeaveManagementSystem/Views/Employee/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<LeaveManagementSystem.Models.ViewModel.EmployeeListViewModel>


<p>
    @Html.ActionLink("Create New", "Create")
</p>

<h2>Employee Details</h2>
<table class="table table-dark">
    <thead>
        <tr>
            
            <th scope="col">Name</th>
            <th scope="col">Contact</th>
            <th scope="col">Designation</th>
     @*       <th scope="col">Joining Date</th>
            <th scope="col">Department </th>
            <th scope="col"> Designation</th>*@

            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td>@Html.DisplayFor(modelItem => item.Name)</td>
                <td>@Html.DisplayFor(modelItem => item.ContactNumber)</td>
                <td>@Html.DisplayFor(modelItem => item.DesignationName)</td>
                @*<td>@Html.DisplayFor(modelItem => item.DateOfJoin)</td>
                <td>@Html.DisplayFor(modelItem => item.DepartmentName)</td>
                <td>@Html.DisplayFor(modelItem => item.DesignationName)</td>*@
                @*<td><a class="btn btn-primary" href="@Url.Action("Create", "Leave")">Apply Leave</a></td>
                <td>*@
                <td class="text-center">
                    <a asp-controller="Leave" asp-action="Create" class="btn btn-primary" asp-route-Id="@item.Id">Apply Leave</a>
                </td>
                <td class="text-center">
                    <a asp-action="Edit" class="btn btn-primary" asp-route-Id="@item.Id">Edit</a>
                </td>
                <td class="text-center">
                    <a asp-action="Details" class="btn btn-info" asp-route-Id="@item.Id">Details</a>
                </td>
                <td class="text-center">
                    <a asp-action="Delete" class="btn btn-danger" asp-route-Id="@item.Id">Delete</a>
                </td>
                
            </tr>
        }
    </tbody>
</table>

@*
@foreach (var item in Model)
{

    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title"> @Html.DisplayFor(modelItem => item.Name)</h5>
            <h3 class="card-body"> @Html.DisplayFor(x => item.xxx)</h3>

            <a class="btn btn-primary" href="@Url.Action("Create", "Leave")">Apply Leave</a>
        </div>
    </div>





}*@